name: Build Docker Images

on:
  workflow_dispatch:
  push:
    paths:
        gpus/amd_nvidia/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: amd_nvidia
            platform: linux/amd64
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dynamyc010/beszel-agent-gpus
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./gpus/${{ matrix.name }}
          file: ./gpus/${{ matrix.name }}/Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true 
          tags: |
            ghcr.io/dynamyc010/beszel-agent-gpus:latest-${{ matrix.name }}
            ghcr.io/dynamyc010/beszel-agent-gpus:${{ matrix.name }}-${{ github.sha }}
            ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
